FROM frolvlad/alpine-gxx
VOLUME /Users/alpha/Desktop/programs/tester/task:/task
WORKDIR /task
CMD sh -c "echo 'Hello, World!'"
# CMD bash -c "g++ main.cpp > comp.txt 2> err-comp.txt" && \
#     ./a.out
